// Auto-generated by `npx supabase gen types typescript`
// Re-run after each migration: npx supabase gen types typescript --local > apps/web/types/database.ts
export type Database = Record<string, never>;
